#!/bin/zsh

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    startx
fi

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# curl -s -g GET 'https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT' | jq .price | xargs cowsay -r
#

zet() {
    cd ${HOME}/Documents/zettel && fzf | xargs -r -I % ${EDITOR} %
}
