#! /bin/zsh
export EDITOR=nvim
export QT_QPA_PLATFORMTHEME=gtk3
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.yarn/bin:$PATH
export FZF_DEFAULT_OPTS='--reverse --bind="ctrl-p:toggle-preview"'
export ZSH_DISABLE_COMPFIX=true
export XAUTHORITY=~/.Xauthority
export WM=i3
