export ZSH="$HOME/.oh-my-zsh"
source ~/.zshenv
source ~/.zshalias

ZSH_THEME="robbyrussell"

plugins=(git fzf zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

keychain --quiet --agents ssh id_rsa ~/.ssh/github
source ~/.keychain/${HOST}-sh
