export ZSH="$HOME/.oh-my-zsh"
source ~/.zshenv
source ~/.zshalias

ZSH_THEME="robbyrussell"

plugins=(git fzf zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

eval `keychain --quiet --agents ssh --eval id_rsa`

