#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -n "`/etc/X11/chooser.sh`" ]; then
 command="`/etc/X11/chooser.sh`"
else
 failsafe="yes"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?* ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xset r rate 200 50
xrandr --output DP-2 --mode 1920x1080 --rate 144.00
xwallpaper --zoom ~/Pictures/wallpapers/joker.png
picom --config ~/.config/picom/picom.conf -b

function _dwm {
    slstatus &
    nm-applet &
    redshift-gtk &
    pa-applet &
    dunst &
    exec dwm
}


case "$WM" in
    dwm)
        _dwm
        ;;

    i3)
        exec i3
        ;;

    *)
        _dwm
        ;;
esac

