require "lvim.options"
require "lvim.keymaps"
require "lvim.plugins"
require "lvim.colorscheme"
require "lvim.cmp"
require "lvim.lsp"
require "lvim.nvim-tree"
require "lvim.treesitter"
require "lvim.buffline"
require "lvim.lualine"
require "lvim.toggleterm"
require "lvim.alpha"
require "lvim.indentline"
require "lvim.vimwiki"
require "lvim.autocommands"
require "lvim.fzf"

