require "lvim.options"
require "lvim.keymaps"
require "lvim.plugins"
require "lvim.colorscheme"
require "lvim.cmp"
require "lvim.lsp"
require "lvim.telescope"
require "lvim.nvim-tree"
require "lvim.treesitter"

